import { integer, pgTable, varchar, bigint } from 'drizzle-orm/pg-core';
import { computerSystemTable } from '@/db/models/win-info/computerSystem.table';
import { dateTable } from '@/db/models/win-info/date.table';

export const physicalMemoryTable = pgTable('physical_memory', {
  id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
  Caption: varchar('caption', { length: 256 }),
  Description: varchar('description', { length: 256 }),
  InstallDate: varchar('install_date', { length: 256 }),
  Name: varchar('name', { length: 256 }),
  Status: varchar('status', { length: 256 }),
  CreationClassName: varchar('creation_class_name', { length: 256 }),
  Manufacturer: varchar('manufacturer', { length: 256 }),
  Model: varchar('model', { length: 256 }),
  OtherIdentifyingInfo: varchar('other_identifying_info', { length: 256 }),
  PartNumber: varchar('part_number', { length: 256 }),
  PoweredOn: varchar('powered_on', { length: 256 }),
  SerialNumber: varchar('serial_number', { length: 256 }),
  SKU: varchar('sku', { length: 256 }),
  Tag: varchar('tag', { length: 256 }),
  Version: varchar('version', { length: 256 }),
  HotSwappable: varchar('hot_swappable', { length: 256 }),
  Removable: varchar('removable', { length: 256 }),
  Replaceable: varchar('replaceable', { length: 256 }),
  FormFactor: varchar('form_factor', { length: 256 }),
  BankLabel: varchar('bank_label', { length: 256 }),
  Capacity: bigint('capacity', { mode: 'number' }),
  DataWidth: varchar('data_width', { length: 256 }),
  InterleavePosition: varchar('interleave_position', { length: 256 }),
  MemoryType: varchar('memory_type', { length: 256 }),
  PositionInRow: varchar('position_in_row', { length: 256 }),
  Speed: integer('speed'),
  TotalWidth: varchar('total_width', { length: 256 }),
  Attributes: varchar('attributes', { length: 256 }),
  ConfiguredClockSpeed: varchar('configured_clock_speed', { length: 256 }),
  ConfiguredVoltage: varchar('configured_voltage', { length: 256 }),
  DeviceLocator: varchar('device_locator', { length: 256 }),
  InterleaveDataDepth: varchar('interleave_data_depth', { length: 256 }),
  MaxVoltage: varchar('max_voltage', { length: 256 }),
  MinVoltage: varchar('min_voltage', { length: 256 }),
  SMBIOSMemoryType: varchar('smbios_memory_type', { length: 256 }),
  TypeDetail: varchar('type_detail', { length: 256 }),
  PSComputerName: varchar('ps_computer_name', { length: 256 }),
  ComputerSystemId: integer('computer_system_id').references(
    () => computerSystemTable.id,
  ),
  DateId: integer('date_id').references(() => dateTable.id),
});
