services:
  app:
    container_name: snmp-backend
    image: gitea.sanjuandediosmalaga.es/casjd/snmp-backend:v2
    restart: always
    ports:
      - '3083:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
