CREATE TABLE "lldp_neighbor" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lldp_neighbor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"local_port_num" integer NOT NULL,
	"neighbor_index" integer NOT NULL,
	"chassis_id_subtype" integer,
	"chassis_id" varchar(255),
	"port_id_subtype" integer,
	"port_id" varchar(255),
	"port_desc" varchar(255),
	"sys_name" varchar(255),
	"sys_desc" varchar(1024),
	"sys_cap_supported" varchar(100),
	"sys_cap_enabled" varchar(100),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE UNIQUE INDEX "lldp_neighbor_device_port_idx" ON "lldp_neighbor" ("device_id","local_port_num","neighbor_index");--> statement-breakpoint
ALTER TABLE "lldp_neighbor" ADD CONSTRAINT "lldp_neighbor_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");