CREATE TABLE "base_board" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "base_board_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"manufacturer" varchar(256),
	"model" varchar(256),
	"name" varchar(256),
	"serial_number" varchar(256),
	"sku" varchar(256),
	"product" varchar(256),
	"computer_system_id" integer,
	"date_id" integer
);
--> statement-breakpoint
CREATE TABLE "bios" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bios_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"smbios_bios_version" varchar(256),
	"manufacturer" varchar(256),
	"name" varchar(256),
	"serial_number" varchar(256),
	"version" varchar(256),
	"computer_system_id" integer,
	"date_id" integer
);
--> statement-breakpoint
CREATE TABLE "center" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "center_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"ip_range" varchar(256) UNIQUE
);
--> statement-breakpoint
CREATE TABLE "computer_system" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "computer_system_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) UNIQUE,
	"primary_owner_name" varchar(256),
	"domain" varchar(256),
	"total_physical_memory" bigint,
	"model" varchar(256),
	"manufacturer" varchar(256),
	"center_id" integer
);
--> statement-breakpoint
CREATE TABLE "computer_system_product" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "computer_system_product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"identifying_number" varchar(256),
	"name" varchar(256),
	"vendor" varchar(256),
	"version" varchar(256),
	"caption" varchar(256),
	"computer_system_id" integer,
	"date_id" integer
);
--> statement-breakpoint
CREATE TABLE "date" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "date_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" date DEFAULT now() UNIQUE
);
--> statement-breakpoint
CREATE TABLE "disk_drive" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "disk_drive_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" varchar(256),
	"caption" varchar(256),
	"partitions" numeric,
	"size" bigint,
	"model" varchar(256),
	"computer_system_id" integer,
	"date_id" integer
);
--> statement-breakpoint
CREATE TABLE "installed_applications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "installed_applications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"display_name" varchar(256),
	"display_version" varchar(256),
	"publisher" varchar(256),
	"install_date" date,
	"computer_system_id" integer,
	"date_id" integer
);
--> statement-breakpoint
CREATE TABLE "login" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "login_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"login_time" timestamp with time zone,
	"computer_id" integer,
	"user_id" integer
);
--> statement-breakpoint
CREATE TABLE "network_adapter_config" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "network_adapter_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"service_name" varchar(256),
	"dhcp_enabled" boolean,
	"index" integer,
	"description" varchar(256),
	"date_id" integer,
	"computer_system_id" integer
);
--> statement-breakpoint
CREATE TABLE "network_identity" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "network_identity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" varchar(256),
	"mac_address" varchar(256),
	"ip_address" varchar(256),
	"date_id" integer,
	"computer_system_id" integer
);
--> statement-breakpoint
CREATE TABLE "operating_system" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "operating_system_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"caption" varchar(256),
	"install_date" varchar(256),
	"system_directory" varchar(256),
	"organization" varchar(256),
	"os_architecture" varchar(256),
	"build_number" bigint,
	"registered_user" varchar(256),
	"serial_number" varchar(256),
	"version" varchar(256),
	"date_id" integer,
	"computer_system_id" integer
);
--> statement-breakpoint
CREATE TABLE "physical_memory" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "physical_memory_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"caption" varchar(256),
	"description" varchar(256),
	"install_date" varchar(256),
	"name" varchar(256),
	"status" varchar(256),
	"creation_class_name" varchar(256),
	"manufacturer" varchar(256),
	"model" varchar(256),
	"other_identifying_info" varchar(256),
	"part_number" varchar(256),
	"powered_on" varchar(256),
	"serial_number" varchar(256),
	"sku" varchar(256),
	"tag" varchar(256),
	"version" varchar(256),
	"hot_swappable" varchar(256),
	"removable" varchar(256),
	"replaceable" varchar(256),
	"form_factor" varchar(256),
	"bank_label" varchar(256),
	"capacity" bigint,
	"data_width" varchar(256),
	"interleave_position" varchar(256),
	"memory_type" varchar(256),
	"position_in_row" varchar(256),
	"speed" integer,
	"total_width" varchar(256),
	"attributes" varchar(256),
	"configured_clock_speed" varchar(256),
	"configured_voltage" varchar(256),
	"device_locator" varchar(256),
	"interleave_data_depth" varchar(256),
	"max_voltage" varchar(256),
	"min_voltage" varchar(256),
	"smbios_memory_type" varchar(256),
	"type_detail" varchar(256),
	"ps_computer_name" varchar(256),
	"computer_system_id" integer,
	"date_id" integer
);
--> statement-breakpoint
CREATE TABLE "processor" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "processor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" varchar(256),
	"name" varchar(256),
	"caption" varchar(256),
	"max_clock_speed" varchar(256),
	"number_of_cores" integer,
	"date_id" integer,
	"computer_system_id" integer
);
--> statement-breakpoint
CREATE TABLE "running_service" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "running_service_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"display_name" varchar(256),
	"status" varchar(256),
	"start_type" varchar(256),
	"date_id" integer,
	"computer_system_id" integer
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(256) UNIQUE
);
--> statement-breakpoint
ALTER TABLE "base_board" ADD CONSTRAINT "base_board_computer_system_id_computer_system_id_fkey" FOREIGN KEY ("computer_system_id") REFERENCES "computer_system"("id");--> statement-breakpoint
ALTER TABLE "base_board" ADD CONSTRAINT "base_board_date_id_date_id_fkey" FOREIGN KEY ("date_id") REFERENCES "date"("id");--> statement-breakpoint
ALTER TABLE "bios" ADD CONSTRAINT "bios_computer_system_id_computer_system_id_fkey" FOREIGN KEY ("computer_system_id") REFERENCES "computer_system"("id");--> statement-breakpoint
ALTER TABLE "bios" ADD CONSTRAINT "bios_date_id_date_id_fkey" FOREIGN KEY ("date_id") REFERENCES "date"("id");--> statement-breakpoint
ALTER TABLE "computer_system" ADD CONSTRAINT "computer_system_center_id_center_id_fkey" FOREIGN KEY ("center_id") REFERENCES "center"("id");--> statement-breakpoint
ALTER TABLE "computer_system_product" ADD CONSTRAINT "computer_system_product_ihOoGGZmeMZr_fkey" FOREIGN KEY ("computer_system_id") REFERENCES "computer_system"("id");--> statement-breakpoint
ALTER TABLE "computer_system_product" ADD CONSTRAINT "computer_system_product_date_id_date_id_fkey" FOREIGN KEY ("date_id") REFERENCES "date"("id");--> statement-breakpoint
ALTER TABLE "disk_drive" ADD CONSTRAINT "disk_drive_computer_system_id_computer_system_id_fkey" FOREIGN KEY ("computer_system_id") REFERENCES "computer_system"("id");--> statement-breakpoint
ALTER TABLE "disk_drive" ADD CONSTRAINT "disk_drive_date_id_date_id_fkey" FOREIGN KEY ("date_id") REFERENCES "date"("id");--> statement-breakpoint
ALTER TABLE "installed_applications" ADD CONSTRAINT "installed_applications_qJ1hprFFzFW0_fkey" FOREIGN KEY ("computer_system_id") REFERENCES "computer_system"("id");--> statement-breakpoint
ALTER TABLE "installed_applications" ADD CONSTRAINT "installed_applications_date_id_date_id_fkey" FOREIGN KEY ("date_id") REFERENCES "date"("id");--> statement-breakpoint
ALTER TABLE "login" ADD CONSTRAINT "login_computer_id_computer_system_id_fkey" FOREIGN KEY ("computer_id") REFERENCES "computer_system"("id");--> statement-breakpoint
ALTER TABLE "login" ADD CONSTRAINT "login_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "network_adapter_config" ADD CONSTRAINT "network_adapter_config_date_id_date_id_fkey" FOREIGN KEY ("date_id") REFERENCES "date"("id");--> statement-breakpoint
ALTER TABLE "network_adapter_config" ADD CONSTRAINT "network_adapter_config_obafaAV72dct_fkey" FOREIGN KEY ("computer_system_id") REFERENCES "computer_system"("id");--> statement-breakpoint
ALTER TABLE "network_identity" ADD CONSTRAINT "network_identity_date_id_date_id_fkey" FOREIGN KEY ("date_id") REFERENCES "date"("id");--> statement-breakpoint
ALTER TABLE "network_identity" ADD CONSTRAINT "network_identity_computer_system_id_computer_system_id_fkey" FOREIGN KEY ("computer_system_id") REFERENCES "computer_system"("id");--> statement-breakpoint
ALTER TABLE "operating_system" ADD CONSTRAINT "operating_system_date_id_date_id_fkey" FOREIGN KEY ("date_id") REFERENCES "date"("id");--> statement-breakpoint
ALTER TABLE "operating_system" ADD CONSTRAINT "operating_system_computer_system_id_computer_system_id_fkey" FOREIGN KEY ("computer_system_id") REFERENCES "computer_system"("id");--> statement-breakpoint
ALTER TABLE "physical_memory" ADD CONSTRAINT "physical_memory_computer_system_id_computer_system_id_fkey" FOREIGN KEY ("computer_system_id") REFERENCES "computer_system"("id");--> statement-breakpoint
ALTER TABLE "physical_memory" ADD CONSTRAINT "physical_memory_date_id_date_id_fkey" FOREIGN KEY ("date_id") REFERENCES "date"("id");--> statement-breakpoint
ALTER TABLE "processor" ADD CONSTRAINT "processor_date_id_date_id_fkey" FOREIGN KEY ("date_id") REFERENCES "date"("id");--> statement-breakpoint
ALTER TABLE "processor" ADD CONSTRAINT "processor_computer_system_id_computer_system_id_fkey" FOREIGN KEY ("computer_system_id") REFERENCES "computer_system"("id");--> statement-breakpoint
ALTER TABLE "running_service" ADD CONSTRAINT "running_service_date_id_date_id_fkey" FOREIGN KEY ("date_id") REFERENCES "date"("id");--> statement-breakpoint
ALTER TABLE "running_service" ADD CONSTRAINT "running_service_computer_system_id_computer_system_id_fkey" FOREIGN KEY ("computer_system_id") REFERENCES "computer_system"("id");