CREATE TABLE "route" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "route_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"dest" varchar(100) NOT NULL,
	"mask" varchar(100),
	"pfx_len" integer,
	"next_hop" varchar(100) NOT NULL,
	"if_index" integer,
	"type" integer,
	"proto" integer,
	"age" integer,
	"metric1" integer,
	"metric2" integer,
	"metric3" integer,
	"metric4" integer,
	"metric5" integer,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE UNIQUE INDEX "route_device_dest_hop_idx" ON "route" ("device_id","dest","next_hop");--> statement-breakpoint
ALTER TABLE "route" ADD CONSTRAINT "route_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");