CREATE TABLE "bridge_fdb_q" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bridge_fdb_q_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"vlan_id" integer NOT NULL,
	"address" varchar(100) NOT NULL,
	"port" integer NOT NULL,
	"status" integer,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "vlan" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vlan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"vlan_id" integer NOT NULL,
	"name" varchar(255),
	"egress_ports" varchar(1024),
	"untagged_ports" varchar(1024),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "bridge_port" ADD COLUMN "pvid" integer;--> statement-breakpoint
CREATE UNIQUE INDEX "bridge_fdb_q_device_vlan_addr_idx" ON "bridge_fdb_q" ("device_id","vlan_id","address");--> statement-breakpoint
CREATE UNIQUE INDEX "vlan_device_vlan_idx" ON "vlan" ("device_id","vlan_id");--> statement-breakpoint
ALTER TABLE "bridge_fdb_q" ADD CONSTRAINT "bridge_fdb_q_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "vlan" ADD CONSTRAINT "vlan_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");