CREATE TABLE "device_tag" (
	"device_id" integer,
	"tag_id" integer,
	CONSTRAINT "device_tag_pkey" PRIMARY KEY("device_id","tag_id")
);
--> statement-breakpoint
CREATE TABLE "tag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL UNIQUE,
	"color" varchar(7)
);
--> statement-breakpoint
ALTER TABLE "device_tag" ADD CONSTRAINT "device_tag_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "device_tag" ADD CONSTRAINT "device_tag_tag_id_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "tag"("id") ON DELETE CASCADE;