CREATE TABLE "device" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "device_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ipv4" varchar(15) NOT NULL UNIQUE,
	"name" varchar(100),
	"subnet_id" integer NOT NULL,
	"snmp_auth_id" integer
);
--> statement-breakpoint
CREATE TABLE "device_metric_instances" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "device_metric_instances_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"metric_object_id" integer NOT NULL,
	"instance_index" varchar(100) DEFAULT '0' NOT NULL,
	"custom_name" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "interface_data" (
	"interface_id" integer NOT NULL,
	"time" timestamp with time zone DEFAULT now() NOT NULL,
	"if_admin_status" integer,
	"if_oper_status" integer,
	"if_in_octets" bigint,
	"if_out_octets" bigint,
	"if_in_errors" integer,
	"if_out_errors" integer
);
--> statement-breakpoint
CREATE TABLE "interface" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "interface_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"interface_index" integer NOT NULL,
	"if_descr" varchar(255),
	"if_name" varchar(255),
	"if_type" integer,
	"if_mtu" integer,
	"if_speed" bigint,
	"if_phys_address" varchar(100),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ip_addr_entry" (
	"ip_snmp_id" integer NOT NULL,
	"time" timestamp with time zone NOT NULL,
	"ip_ad_ent_addr" varchar(20) NOT NULL,
	"ip_ad_ent_if_index" integer NOT NULL,
	"ip_ad_ent_net_mask" varchar(20) NOT NULL,
	"ip_ad_ent_bcast_addr" varchar(20) NOT NULL,
	"ip_ad_ent_reasm_max_size" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ip_net_to_media_table" (
	"ip_snmp_id" integer NOT NULL,
	"time" timestamp with time zone NOT NULL,
	"ip_net_to_media_if_index" integer NOT NULL,
	"ip_net_to_media_phys_address" varchar(20) NOT NULL,
	"ip_net_to_media_net_address" varchar(20) NOT NULL,
	"ip_net_to_media_type" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ip_snmp" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ip_snmp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hr_sw_installed_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hr_sw_installed_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" timestamp with time zone NOT NULL,
	"hr_sw_installed_index" integer NOT NULL,
	"hr_sw_installed_name" varchar(255) NOT NULL,
	"hr_sw_installed_id" varchar(255) NOT NULL,
	"hr_sw_installed_type" integer NOT NULL,
	"hr_sw_installed_date" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hr_sw_run_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hr_sw_run_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" timestamp with time zone NOT NULL,
	"hr_sw_run_index" integer NOT NULL,
	"hr_sw_run_name" varchar(255) NOT NULL,
	"hr_sw_run_id" varchar(255) NOT NULL,
	"hr_sw_run_path" varchar(255) NOT NULL,
	"hr_sw_run_parameters" varchar(255) NOT NULL,
	"hr_sw_run_type" integer NOT NULL,
	"hr_sw_run_status" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hr_sw_run_perf_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hr_sw_run_perf_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" timestamp with time zone NOT NULL,
	"hr_sw_run_perf_cpu" integer NOT NULL,
	"hr_sw_run_perf_mem" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "resource" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "resource_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"value" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "system" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "system_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"sys_descr" varchar(255),
	"sys_up_time" timestamp with time zone,
	"sys_contact" varchar(255),
	"sys_name" varchar(255),
	"sys_location" varchar(255),
	"sys_services" integer
);
--> statement-breakpoint
CREATE TABLE "metric_objects" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "metric_objects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"metrics_definition_id" integer NOT NULL,
	"name" varchar(100) NOT NULL,
	"oid_base" varchar(500) NOT NULL,
	"data_type" varchar(50) NOT NULL,
	"unit" varchar(20)
);
--> statement-breakpoint
CREATE TABLE "metrics_definition" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "metrics_definition_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"description" varchar(500),
	"oid" varchar(500) NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "snmp_auth" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "snmp_auth_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"version" varchar NOT NULL,
	"port" integer DEFAULT 161 NOT NULL,
	"community" varchar NOT NULL,
	"v3_user" varchar NOT NULL,
	"v3_auth_protocol" varchar NOT NULL,
	"v3_auth_key" varchar NOT NULL,
	"v3_priv_protocol" varchar NOT NULL,
	"v3_priv_key" varchar NOT NULL,
	"v3_level" varchar NOT NULL
);
--> statement-breakpoint
CREATE TABLE "snmp_data" (
	"device_metric_instance_id" integer NOT NULL,
	"time" timestamp with time zone DEFAULT now() NOT NULL,
	"value_num" double precision,
	"value_str" text
);
--> statement-breakpoint
CREATE TABLE "subnet" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subnet_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cidr" varchar(15) NOT NULL,
	"name" varchar(100)
);
--> statement-breakpoint
ALTER TABLE "device" ADD CONSTRAINT "device_subnet_id_subnet_id_fkey" FOREIGN KEY ("subnet_id") REFERENCES "subnet"("id");--> statement-breakpoint
ALTER TABLE "device" ADD CONSTRAINT "device_snmp_auth_id_snmp_auth_id_fkey" FOREIGN KEY ("snmp_auth_id") REFERENCES "snmp_auth"("id");--> statement-breakpoint
ALTER TABLE "device_metric_instances" ADD CONSTRAINT "device_metric_instances_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "device_metric_instances" ADD CONSTRAINT "device_metric_instances_metric_object_id_metric_objects_id_fkey" FOREIGN KEY ("metric_object_id") REFERENCES "metric_objects"("id");--> statement-breakpoint
ALTER TABLE "interface_data" ADD CONSTRAINT "interface_data_interface_id_interface_id_fkey" FOREIGN KEY ("interface_id") REFERENCES "interface"("id");--> statement-breakpoint
ALTER TABLE "interface" ADD CONSTRAINT "interface_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "ip_addr_entry" ADD CONSTRAINT "ip_addr_entry_ip_snmp_id_ip_snmp_id_fkey" FOREIGN KEY ("ip_snmp_id") REFERENCES "ip_snmp"("id");--> statement-breakpoint
ALTER TABLE "ip_net_to_media_table" ADD CONSTRAINT "ip_net_to_media_table_ip_snmp_id_ip_snmp_id_fkey" FOREIGN KEY ("ip_snmp_id") REFERENCES "ip_snmp"("id");--> statement-breakpoint
ALTER TABLE "ip_snmp" ADD CONSTRAINT "ip_snmp_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "resource" ADD CONSTRAINT "resource_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "system" ADD CONSTRAINT "system_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "metric_objects" ADD CONSTRAINT "metric_objects_metrics_definition_id_metrics_definition_id_fkey" FOREIGN KEY ("metrics_definition_id") REFERENCES "metrics_definition"("id");--> statement-breakpoint
ALTER TABLE "snmp_data" ADD CONSTRAINT "snmp_data_rB6RTuZl5nUY_fkey" FOREIGN KEY ("device_metric_instance_id") REFERENCES "device_metric_instances"("id");