CREATE TABLE "bridge_base" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bridge_base_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"bridge_address" varchar(100),
	"num_ports" integer,
	"type" integer,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "bridge_fdb" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bridge_fdb_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"address" varchar(100) NOT NULL,
	"port" integer NOT NULL,
	"status" integer,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "bridge_port" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bridge_port_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"bridge_port" integer NOT NULL,
	"if_index" integer,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
DROP TABLE "device_metric_instances";--> statement-breakpoint
CREATE UNIQUE INDEX "bridge_base_device_idx" ON "bridge_base" ("device_id");--> statement-breakpoint
CREATE UNIQUE INDEX "bridge_fdb_device_addr_idx" ON "bridge_fdb" ("device_id","address");--> statement-breakpoint
CREATE UNIQUE INDEX "bridge_port_device_port_idx" ON "bridge_port" ("device_id","bridge_port");--> statement-breakpoint
ALTER TABLE "bridge_base" ADD CONSTRAINT "bridge_base_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "bridge_fdb" ADD CONSTRAINT "bridge_fdb_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "bridge_port" ADD CONSTRAINT "bridge_port_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");