CREATE TABLE "cdp_neighbor" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cdp_neighbor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"if_index" integer NOT NULL,
	"neighbor_index" integer NOT NULL,
	"address" varchar(100),
	"neighbor_device_id" varchar(255),
	"neighbor_port" varchar(255),
	"neighbor_platform" varchar(255),
	"neighbor_sys_name" varchar(255),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE UNIQUE INDEX "cdp_neighbor_device_if_idx" ON "cdp_neighbor" ("device_id","if_index","neighbor_index");--> statement-breakpoint
ALTER TABLE "cdp_neighbor" ADD CONSTRAINT "cdp_neighbor_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");