CREATE TABLE "bridge_base" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bridge_base_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"bridge_address" varchar(100),
	"num_ports" integer,
	"type" integer,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "bridge_fdb_q" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bridge_fdb_q_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"vlan_id" integer NOT NULL,
	"address" varchar(100) NOT NULL,
	"port" integer NOT NULL,
	"status" integer,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "bridge_fdb" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bridge_fdb_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"address" varchar(100) NOT NULL,
	"port" integer NOT NULL,
	"status" integer,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "bridge_port" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bridge_port_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"bridge_port" integer NOT NULL,
	"if_index" integer,
	"pvid" integer,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "vlan" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vlan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"vlan_id" integer NOT NULL,
	"name" varchar(255),
	"egress_ports" text,
	"untagged_ports" text,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "cdp_neighbor" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cdp_neighbor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"interface_id" integer,
	"if_index" integer NOT NULL,
	"neighbor_index" integer NOT NULL,
	"address" varchar(100),
	"neighbor_device_id" varchar(255),
	"neighbor_port" varchar(255),
	"neighbor_platform" varchar(255),
	"neighbor_sys_name" varchar(255),
	"remote_device_id" integer,
	"remote_interface_id" integer,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "device" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "device_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ipv4" varchar(15) NOT NULL UNIQUE,
	"name" varchar(100),
	"subnet_id" integer NOT NULL,
	"snmp_auth_id" integer
);
--> statement-breakpoint
CREATE TABLE "entity_physical" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "entity_physical_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"physical_index" integer NOT NULL,
	"descr" varchar(255),
	"vendor_type" varchar(255),
	"contained_in" integer,
	"class" integer,
	"parent_rel_pos" integer,
	"name" varchar(255),
	"hardware_rev" varchar(255),
	"firmware_rev" varchar(255),
	"software_rev" varchar(255),
	"serial_num" varchar(255),
	"mfg_name" varchar(255),
	"model_name" varchar(255),
	"alias" varchar(255),
	"asset_id" varchar(255),
	"is_fru" integer,
	"mfg_date" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "interface_data" (
	"interface_id" integer NOT NULL,
	"time" timestamp with time zone DEFAULT now() NOT NULL,
	"if_admin_status" integer,
	"if_oper_status" integer,
	"if_in_octets" numeric,
	"if_out_octets" numeric,
	"if_in_errors" integer,
	"if_out_errors" integer
);
--> statement-breakpoint
CREATE TABLE "interface" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "interface_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"if_index" integer NOT NULL,
	"if_descr" varchar(255),
	"if_name" varchar(255),
	"if_type" integer,
	"if_mtu" integer,
	"if_speed" numeric,
	"if_phys_address" varchar(100),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ip_addr_entry" (
	"ip_snmp_id" integer NOT NULL,
	"time" timestamp with time zone NOT NULL,
	"ip_ad_ent_addr" varchar(20) NOT NULL,
	"ip_ad_ent_if_index" integer NOT NULL,
	"ip_ad_ent_net_mask" varchar(20) NOT NULL,
	"ip_ad_ent_bcast_addr" varchar(20) NOT NULL,
	"ip_ad_ent_reasm_max_size" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ip_net_to_media_table" (
	"ip_snmp_id" integer NOT NULL,
	"time" timestamp with time zone NOT NULL,
	"ip_net_to_media_if_index" integer NOT NULL,
	"ip_net_to_media_phys_address" varchar(20) NOT NULL,
	"ip_net_to_media_net_address" varchar(20) NOT NULL,
	"ip_net_to_media_type" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ip_snmp" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ip_snmp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "lldp_neighbor" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lldp_neighbor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"interface_id" integer NOT NULL,
	"lldp_rem_chassis_id" varchar(255),
	"lldp_rem_port_id_subtype" integer,
	"lldp_rem_port_id" varchar(255),
	"lldp_rem_sys_name" varchar(255),
	"remote_device_id" integer,
	"remote_interface_id" integer,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "hr_sw_installed_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hr_sw_installed_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"resource_id" integer NOT NULL,
	"date" timestamp with time zone NOT NULL,
	"hr_sw_installed_index" integer NOT NULL,
	"hr_sw_installed_name" varchar(255) NOT NULL,
	"hr_sw_installed_id" varchar(255) NOT NULL,
	"hr_sw_installed_type" integer NOT NULL,
	"hr_sw_installed_date" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hr_sw_run_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hr_sw_run_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"resource_id" integer NOT NULL,
	"date" timestamp with time zone NOT NULL,
	"hr_sw_run_index" integer NOT NULL,
	"hr_sw_run_name" varchar(255) NOT NULL,
	"hr_sw_run_id" varchar(255) NOT NULL,
	"hr_sw_run_path" varchar(255) NOT NULL,
	"hr_sw_run_parameters" varchar(255) NOT NULL,
	"hr_sw_run_type" integer NOT NULL,
	"hr_sw_run_status" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hr_sw_run_perf_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hr_sw_run_perf_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"resource_id" integer NOT NULL,
	"date" timestamp with time zone NOT NULL,
	"hr_sw_run_index" integer NOT NULL,
	"hr_sw_run_perf_cpu" integer NOT NULL,
	"hr_sw_run_perf_mem" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "resource" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "resource_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"value" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "route" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "route_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"dest" varchar(100) NOT NULL,
	"mask" varchar(100),
	"pfx_len" integer,
	"next_hop" varchar(100) NOT NULL,
	"if_index" integer,
	"type" integer,
	"proto" integer,
	"age" integer,
	"metric1" integer,
	"metric2" integer,
	"metric3" integer,
	"metric4" integer,
	"metric5" integer,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "system" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "system_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"sys_descr" varchar(255),
	"sys_up_time" timestamp with time zone,
	"sys_contact" varchar(255),
	"sys_name" varchar(255),
	"sys_location" varchar(255),
	"sys_services" integer
);
--> statement-breakpoint
CREATE TABLE "metric_objects" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "metric_objects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"metrics_definition_id" integer NOT NULL,
	"name" varchar(100) NOT NULL,
	"oid_base" varchar(500) NOT NULL,
	"data_type" varchar(50) NOT NULL,
	"unit" varchar(20)
);
--> statement-breakpoint
CREATE TABLE "metrics_definition" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "metrics_definition_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"description" varchar(500),
	"oid" varchar(500) NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "snmp_auth" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "snmp_auth_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"version" varchar NOT NULL,
	"port" integer DEFAULT 161 NOT NULL,
	"community" varchar NOT NULL,
	"v3_user" varchar,
	"v3_auth_protocol" varchar,
	"v3_auth_key" varchar,
	"v3_priv_protocol" varchar,
	"v3_priv_key" varchar,
	"v3_level" varchar
);
--> statement-breakpoint
CREATE TABLE "subnet" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subnet_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cidr" varchar(15) NOT NULL,
	"name" varchar(100)
);
--> statement-breakpoint
CREATE UNIQUE INDEX "bridge_base_device_idx" ON "bridge_base" ("device_id");--> statement-breakpoint
CREATE UNIQUE INDEX "bridge_fdb_q_device_vlan_addr_idx" ON "bridge_fdb_q" ("device_id","vlan_id","address");--> statement-breakpoint
CREATE UNIQUE INDEX "bridge_fdb_device_addr_idx" ON "bridge_fdb" ("device_id","address");--> statement-breakpoint
CREATE UNIQUE INDEX "bridge_port_device_port_idx" ON "bridge_port" ("device_id","bridge_port");--> statement-breakpoint
CREATE UNIQUE INDEX "vlan_device_vlan_idx" ON "vlan" ("device_id","vlan_id");--> statement-breakpoint
CREATE UNIQUE INDEX "cdp_neighbor_device_if_idx" ON "cdp_neighbor" ("device_id","if_index","neighbor_index");--> statement-breakpoint
CREATE UNIQUE INDEX "entity_physical_device_idx" ON "entity_physical" ("device_id","physical_index");--> statement-breakpoint
CREATE UNIQUE INDEX "device_interface_idx" ON "interface" ("device_id","if_index");--> statement-breakpoint
CREATE UNIQUE INDEX "device_interface_mac_idx" ON "interface" ("device_id","if_phys_address") WHERE if_phys_address IS NOT NULL AND if_phys_address != '' AND if_phys_address != '00:00:00:00:00:00' AND if_phys_address != '00:00:00:00:00:00:00:00';--> statement-breakpoint
CREATE UNIQUE INDEX "ip_addr_entry_idx" ON "ip_addr_entry" ("ip_snmp_id","ip_ad_ent_addr");--> statement-breakpoint
CREATE UNIQUE INDEX "ip_net_media_idx" ON "ip_net_to_media_table" ("ip_snmp_id","ip_net_to_media_if_index","ip_net_to_media_net_address");--> statement-breakpoint
CREATE UNIQUE INDEX "device_ip_snmp_idx" ON "ip_snmp" ("device_id");--> statement-breakpoint
CREATE UNIQUE INDEX "lldp_neighbor_device_port_idx" ON "lldp_neighbor" ("device_id","interface_id");--> statement-breakpoint
CREATE UNIQUE INDEX "resource_app_name_idx" ON "hr_sw_installed_entry" ("resource_id","hr_sw_installed_name");--> statement-breakpoint
CREATE UNIQUE INDEX "device_resource_unq_idx" ON "resource" ("device_id","name","type");--> statement-breakpoint
CREATE UNIQUE INDEX "route_device_dest_hop_idx" ON "route" ("device_id","dest","next_hop");--> statement-breakpoint
CREATE UNIQUE INDEX "device_system_idx" ON "system" ("device_id");--> statement-breakpoint
ALTER TABLE "bridge_base" ADD CONSTRAINT "bridge_base_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "bridge_fdb_q" ADD CONSTRAINT "bridge_fdb_q_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "bridge_fdb" ADD CONSTRAINT "bridge_fdb_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "bridge_port" ADD CONSTRAINT "bridge_port_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "vlan" ADD CONSTRAINT "vlan_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "cdp_neighbor" ADD CONSTRAINT "cdp_neighbor_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "cdp_neighbor" ADD CONSTRAINT "cdp_neighbor_interface_id_interface_id_fkey" FOREIGN KEY ("interface_id") REFERENCES "interface"("id");--> statement-breakpoint
ALTER TABLE "cdp_neighbor" ADD CONSTRAINT "cdp_neighbor_remote_device_id_device_id_fkey" FOREIGN KEY ("remote_device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "cdp_neighbor" ADD CONSTRAINT "cdp_neighbor_remote_interface_id_interface_id_fkey" FOREIGN KEY ("remote_interface_id") REFERENCES "interface"("id");--> statement-breakpoint
ALTER TABLE "device" ADD CONSTRAINT "device_subnet_id_subnet_id_fkey" FOREIGN KEY ("subnet_id") REFERENCES "subnet"("id");--> statement-breakpoint
ALTER TABLE "device" ADD CONSTRAINT "device_snmp_auth_id_snmp_auth_id_fkey" FOREIGN KEY ("snmp_auth_id") REFERENCES "snmp_auth"("id");--> statement-breakpoint
ALTER TABLE "entity_physical" ADD CONSTRAINT "entity_physical_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "interface_data" ADD CONSTRAINT "interface_data_interface_id_interface_id_fkey" FOREIGN KEY ("interface_id") REFERENCES "interface"("id");--> statement-breakpoint
ALTER TABLE "interface" ADD CONSTRAINT "interface_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "ip_addr_entry" ADD CONSTRAINT "ip_addr_entry_ip_snmp_id_ip_snmp_id_fkey" FOREIGN KEY ("ip_snmp_id") REFERENCES "ip_snmp"("id");--> statement-breakpoint
ALTER TABLE "ip_net_to_media_table" ADD CONSTRAINT "ip_net_to_media_table_ip_snmp_id_ip_snmp_id_fkey" FOREIGN KEY ("ip_snmp_id") REFERENCES "ip_snmp"("id");--> statement-breakpoint
ALTER TABLE "ip_snmp" ADD CONSTRAINT "ip_snmp_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "lldp_neighbor" ADD CONSTRAINT "lldp_neighbor_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "lldp_neighbor" ADD CONSTRAINT "lldp_neighbor_interface_id_interface_id_fkey" FOREIGN KEY ("interface_id") REFERENCES "interface"("id");--> statement-breakpoint
ALTER TABLE "lldp_neighbor" ADD CONSTRAINT "lldp_neighbor_remote_device_id_device_id_fkey" FOREIGN KEY ("remote_device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "lldp_neighbor" ADD CONSTRAINT "lldp_neighbor_remote_interface_id_interface_id_fkey" FOREIGN KEY ("remote_interface_id") REFERENCES "interface"("id");--> statement-breakpoint
ALTER TABLE "hr_sw_installed_entry" ADD CONSTRAINT "hr_sw_installed_entry_resource_id_resource_id_fkey" FOREIGN KEY ("resource_id") REFERENCES "resource"("id");--> statement-breakpoint
ALTER TABLE "hr_sw_run_entry" ADD CONSTRAINT "hr_sw_run_entry_resource_id_resource_id_fkey" FOREIGN KEY ("resource_id") REFERENCES "resource"("id");--> statement-breakpoint
ALTER TABLE "hr_sw_run_perf_entry" ADD CONSTRAINT "hr_sw_run_perf_entry_resource_id_resource_id_fkey" FOREIGN KEY ("resource_id") REFERENCES "resource"("id");--> statement-breakpoint
ALTER TABLE "resource" ADD CONSTRAINT "resource_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "route" ADD CONSTRAINT "route_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "system" ADD CONSTRAINT "system_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");--> statement-breakpoint
ALTER TABLE "metric_objects" ADD CONSTRAINT "metric_objects_metrics_definition_id_metrics_definition_id_fkey" FOREIGN KEY ("metrics_definition_id") REFERENCES "metrics_definition"("id");--> statement-breakpoint
CREATE VIEW "lldp_view" AS (select "lldp_neighbor"."id" as "id", "lldp_neighbor"."device_id" as "local_device_id", "local_device"."name" as "local_device_name", "local_device"."ipv4" as "local_device_ipv4", "lldp_neighbor"."interface_id" as "local_interface_id", "local_interface"."if_name" as "local_interface_name", "local_interface"."if_descr" as "local_interface_desc", "lldp_neighbor"."lldp_rem_sys_name" as "neighbor_sys_name", "lldp_neighbor"."lldp_rem_port_id" as "neighbor_port_id", "lldp_neighbor"."lldp_rem_chassis_id" as "neighbor_chassis_id", "lldp_neighbor"."remote_device_id" as "remote_device_id", "remote_device"."name" as "remote_device_name", "remote_device"."ipv4" as "remote_device_ipv4", "lldp_neighbor"."remote_interface_id" as "remote_interface_id", "remote_interface"."if_name" as "remote_interface_name", "lldp_neighbor"."updated_at" as "updated_at" from "lldp_neighbor" left join "device" "local_device" on "lldp_neighbor"."device_id" = "local_device"."id" left join "interface" "local_interface" on "lldp_neighbor"."interface_id" = "local_interface"."id" left join "device" "remote_device" on "lldp_neighbor"."remote_device_id" = "remote_device"."id" left join "interface" "remote_interface" on "lldp_neighbor"."remote_interface_id" = "remote_interface"."id");