CREATE TABLE "komodo_auth" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "komodo_auth_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"url" varchar NOT NULL,
	"key" varchar NOT NULL,
	"secret" varchar NOT NULL
);
--> statement-breakpoint
CREATE TABLE "npm_auth" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "npm_auth_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"url" varchar NOT NULL,
	"username" varchar NOT NULL,
	"password" varchar NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pangolin_auth" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pangolin_auth_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"url" varchar NOT NULL,
	"token" varchar NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pangolin_org" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pangolin_org_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar NOT NULL UNIQUE,
	"slug" varchar NOT NULL UNIQUE,
	"auth_id" integer NOT NULL
);
--> statement-breakpoint
DROP VIEW "lldp_view";--> statement-breakpoint
ALTER TABLE "pangolin_org" ADD CONSTRAINT "pangolin_org_auth_id_pangolin_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "pangolin_auth"("id");