CREATE TABLE "location" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "location_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL UNIQUE,
	"description" varchar(500),
	"parent_id" integer
);
--> statement-breakpoint
ALTER TABLE "device" ADD COLUMN "location_id" integer;--> statement-breakpoint
ALTER TABLE "device" ADD CONSTRAINT "device_location_id_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "location"("id");--> statement-breakpoint
ALTER TABLE "location" ADD CONSTRAINT "location_parent_id_location_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "location"("id");