CREATE TABLE "entity_physical" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "entity_physical_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"physical_index" integer NOT NULL,
	"descr" varchar(255),
	"vendor_type" varchar(255),
	"contained_in" integer,
	"class" integer,
	"parent_rel_pos" integer,
	"name" varchar(255),
	"hardware_rev" varchar(255),
	"firmware_rev" varchar(255),
	"software_rev" varchar(255),
	"serial_num" varchar(255),
	"mfg_name" varchar(255),
	"model_name" varchar(255),
	"alias" varchar(255),
	"asset_id" varchar(255),
	"is_fru" integer,
	"mfg_date" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE UNIQUE INDEX "entity_physical_device_idx" ON "entity_physical" ("device_id","physical_index");--> statement-breakpoint
ALTER TABLE "entity_physical" ADD CONSTRAINT "entity_physical_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id");