CREATE TABLE "device" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "device_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ipv4" varchar(15) NOT NULL,
	"name" varchar(100),
	"subnet_id" integer NOT NULL,
	"snmp_id" integer
);
--> statement-breakpoint
CREATE TABLE "snmp" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "snmp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"version" varchar NOT NULL,
	"port" integer DEFAULT 161 NOT NULL,
	"community" varchar NOT NULL,
	"v3_user" varchar NOT NULL,
	"v3_auth_protocol" varchar NOT NULL,
	"v3_auth_key" varchar NOT NULL,
	"v3_priv_protocol" varchar NOT NULL,
	"v3_priv_key" varchar NOT NULL,
	"v3_level" varchar NOT NULL
);
--> statement-breakpoint
CREATE TABLE "subnet" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subnet_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cidr" varchar(15) NOT NULL,
	"name" varchar(100)
);
--> statement-breakpoint
ALTER TABLE "device" ADD CONSTRAINT "device_subnet_id_subnet_id_fkey" FOREIGN KEY ("subnet_id") REFERENCES "subnet"("id");--> statement-breakpoint
ALTER TABLE "device" ADD CONSTRAINT "device_snmp_id_snmp_id_fkey" FOREIGN KEY ("snmp_id") REFERENCES "snmp"("id");