CREATE TABLE "monitor_group_device" (
	"group_id" integer,
	"device_id" integer,
	CONSTRAINT "monitor_group_device_pkey" PRIMARY KEY("group_id","device_id")
);
--> statement-breakpoint
CREATE TABLE "monitor_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monitor_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"description" varchar(500),
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monitor_port_group_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monitor_port_group_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"port_group_id" integer NOT NULL,
	"port" integer NOT NULL,
	"expected_status" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monitor_port_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monitor_port_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"description" varchar(500)
);
--> statement-breakpoint
CREATE TABLE "monitor_rule" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monitor_rule_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"device_group_id" integer NOT NULL,
	"port_group_id" integer NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "port_status" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "port_status_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"device_id" integer NOT NULL,
	"port" integer NOT NULL,
	"status" boolean NOT NULL,
	"response_time" integer,
	"check_time" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "monitor_group_device" ADD CONSTRAINT "monitor_group_device_group_id_monitor_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "monitor_group"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "monitor_group_device" ADD CONSTRAINT "monitor_group_device_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "monitor_port_group_item" ADD CONSTRAINT "monitor_port_group_item_2U4CcgNLj1mj_fkey" FOREIGN KEY ("port_group_id") REFERENCES "monitor_port_group"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "monitor_rule" ADD CONSTRAINT "monitor_rule_device_group_id_monitor_group_id_fkey" FOREIGN KEY ("device_group_id") REFERENCES "monitor_group"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "monitor_rule" ADD CONSTRAINT "monitor_rule_port_group_id_monitor_port_group_id_fkey" FOREIGN KEY ("port_group_id") REFERENCES "monitor_port_group"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "port_status" ADD CONSTRAINT "port_status_device_id_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "device"("id") ON DELETE CASCADE;