CREATE TABLE "notification_action" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_action_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"monitor_rule_id" integer NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"type" varchar NOT NULL,
	"consecutive_failures" integer DEFAULT 1,
	"repeat_interval_mins" integer DEFAULT 60,
	"last_sent_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ntfy_action" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ntfy_action_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"notification_action_id" integer NOT NULL,
	"ntfy_topic_id" integer,
	"title" varchar(256),
	"priority" integer
);
--> statement-breakpoint
CREATE TABLE "ntfy_action_tag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ntfy_action_tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ntfy_action_id" integer NOT NULL,
	"tag" varchar(100) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ntfy_credential" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ntfy_credential_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"base_url" varchar(256) DEFAULT 'https://ntfy.sh' NOT NULL,
	"username" varchar(256),
	"password" varchar(256),
	"token" varchar(256)
);
--> statement-breakpoint
CREATE TABLE "ntfy_topic" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ntfy_topic_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"topic" varchar(256) NOT NULL,
	"credential_id" integer NOT NULL,
	"description" text
);
--> statement-breakpoint
ALTER TABLE "monitor_rule" ADD COLUMN "condition" varchar DEFAULT 'down' NOT NULL;--> statement-breakpoint
ALTER TABLE "notification_action" ADD CONSTRAINT "notification_action_monitor_rule_id_monitor_rule_id_fkey" FOREIGN KEY ("monitor_rule_id") REFERENCES "monitor_rule"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "ntfy_action" ADD CONSTRAINT "ntfy_action_notification_action_id_notification_action_id_fkey" FOREIGN KEY ("notification_action_id") REFERENCES "notification_action"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "ntfy_action" ADD CONSTRAINT "ntfy_action_ntfy_topic_id_ntfy_topic_id_fkey" FOREIGN KEY ("ntfy_topic_id") REFERENCES "ntfy_topic"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "ntfy_action_tag" ADD CONSTRAINT "ntfy_action_tag_ntfy_action_id_ntfy_action_id_fkey" FOREIGN KEY ("ntfy_action_id") REFERENCES "ntfy_action"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "ntfy_topic" ADD CONSTRAINT "ntfy_topic_credential_id_ntfy_credential_id_fkey" FOREIGN KEY ("credential_id") REFERENCES "ntfy_credential"("id") ON DELETE CASCADE;